---
- hosts: elk
  tasks:
   - name: add docker repository
     apt_repository:
       repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
       state: present
       filename: docker
       update_cache: yes

   - name: install docker-engine
     apt: name=docker-engine state=latest force=yes

   - name: install docker-compose
     shell: curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

   - name: add executable permssion to docker-compose
     file: 
       path: /usr/local/bin/docker-compose
       mode: "u+x,g+x,o+x"
  
   - name: add dockerfile and docker-compose-file
     copy: src=Dockerfile dest=/opt/Dockerfile
   - copy: src=docker-compose.yml dest=/opt/docker-compose.yml
   - copy: src=start.sh dest=/opt/start.sh
   - copy: src=logstash.conf dest=/opt/logstash.conf
 
   - name: Execute docker-compose
     shell: docker-compose up -d
     args:
       chdir: /opt

   - name: add beats repository
     apt_repository:
       repo: deb https://packages.elastic.co/beats/apt stable main
       state: present
       filename: beats
       update_cache: yes

   - name: install topbeat
     apt: name=topbeat state=latest force=yes

   - name: copy topbeat.yml
     copy: src=topbeat.yml dest=/etc/topbeat/topbeat.yml

   - name: restart topbeat
     service: name=topbeat state=restarted
